### ISSUE TITLE
MASA.Contrib Roadmap for 0.4.0

### ISSUE THREAD

**Issue by zhenlei520** [masastack/MASA.Contrib#40]
### Roadmap
This issue represents a list of major investments that our team will focus on in the 0.4.0 time frame. It doesn't include all the features and bug fixes we'll be working on in the meantime
这个Issue代表我们团队将在 0.4.0 内重点关注的列表。它不包括我们将在此期间进行的所有功能和错误修复。

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go, but will try to keep this issue up to date to reflect on our progress and learnings.
请注意，这是一个我们希望达到的愿望清单。 其中许多项目需要彻底的调查和设计，这可能会导致我们的计划发生变化。我们最终可能会消减一些东西，并做出改变，但将努力保持这个Issue是最新的，以反映我们的进步和学习。  

The roadmap consists of the following features:
路线图包括以下特性

#### AutoComplete(自动完成)
* [x] Add document operation(get, set, delete)
添加document操作(get, set, delete)

#### Configuration(配置)
* [x] Add IMasaConfiguration to support get the Configuration from the local configuration and configuration api
添加 IMasaConfiguration 支持从本地配置和配置ApiI中获取配置 #36  

#### Ddd.Domain(领域)
* [x] AggregateRoot support domain events #55
聚合根支持领域事件

#### Isolation(隔离性)
* [x] Isolation support physical, logical and tenant #28 #30 #31
隔离性支持物理的, 逻辑的, 租户
* [x] Support environmen isolation #28 #30 #31
支持环境隔离

#### Mapping(映射)
* [x] Support Mapping.Mapster  #50 #51
支持Mapping.Mapster
