### ISSUE TITLE
MASA.Contrib Roadmap for 0.5.0

### ISSUE THREAD

**Issue by zhenlei520** [masastack/MASA.Contrib#42]
### Roadmap
This issue represents a list of major investments that our team will focus on in the 0.5.0 time frame. It doesn't include all the features and bug fixes we'll be working on in the meantime
这个Issue代表我们团队将在 0.5.0 内重点关注的列表。它不包括我们将在此期间进行的所有功能和错误修复。

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go, but will try to keep this issue up to date to reflect on our progress and learnings.
请注意，这是一个我们希望达到的愿望清单。 其中许多项目需要彻底的调查和设计，这可能会导致我们的计划发生变化。我们最终可能会消减一些东西，并做出改变，但将努力保持这个Issue是最新的，以反映我们的进步和学习。  

The roadmap consists of the following features:
路线图包括以下特性

## Ddd.Domain(领域)
* [x] Improve the experience of using AuditEntity #81 
提升AuditEntity的使用体验

## Identity(身份)
* [x] Provide access to user identity information #81 
提供获取用户身份信息

## IdGenerator (Id生成器)
* [x] Support IdGenerator, add SimpleGuid, SequentialGuid, Snowflake implementation #76 
支持IdGenerator，新增SimpleGuid、SequentialGuid、Snowflake 实现  #76 

## EntityFramework
* [x] Fix bugs using MySql #108, Fixed using soft delete filtering to cause deletes to fail due to nested references #144 , support optimistic concurrency #79, refactor MasaDbContextOptionsBuilder #122
修复使用MySql错误 #108 , 修复使用软删除过滤由于嵌套引用导致删除失败 #144, 支持乐观并发 #79, 重构MasaDbContextOptionsBuilder #122

## EventBus (事件总线)

* [x] EventBus: Modify the error message address #105、Fixed the issue that transaction middleware will be executed multiple times when some events (events that do not inherit ITranscation) are published, when there are nested publishing events in Handler #146 #153
[x] EventBus: 修改错误提示信息地址 #105、修复部分事件(未继承ITranscation的事件)发布时，当Handler存在嵌套发布事件时，事务中间件会被多次执行的问题 #146 #153
* [x] IntegrationEvents.Dapr: Refactor DaprIntegrationEventBus #116 #150
重构DaprIntegrationEventBus #116 #150
* [x] DomainEventBus: Fix aggregate root add realm event execution sequence error #120 #135
DomainEventBus: 修复聚合根添加领域事件执行顺序错误 #120 #135

## Identity

* [x] IdentityModel: Support Identity, Blazor is not supported yet  #81 #103 #118
支持Identity，暂不支持Blazor #81 #103 #118

## DistributedLock (分布式锁)

* [x] Support distributed lock #88 #131
支持分布式锁 #88 #131

## Sdks

* [x] Auth: Add sdk methods for teams and permissions #77 #80, update auth sdk identity #84 #98 #117 #141 Add Auth.Contracts #104 #113
为团队和权限添加 sdk 方法 #77 #80, 更新 auth sdk 身份 #84 #98 #117 #141 添加 Auth.Contracts #104 #113 
* [x] OIDC: Add Oidc.EntityFramework、Oidc.Cache.Storage #78 #93 #109
OIDC: 添加Oidc.EntityFramework、Oidc.Cache.Storage #78 #93 #109
* [x] MC: Add Mc Sdk #112 #143
添加消息中心 Sdk #112 #143
* [x] Scheduler: Add Scheduler Sdk #102 #107 #110 #142 #152
Scheduler：添加调度器Sdk  #102 #107 #110 #142 #152
* [x] TSC:  Add Tsc Sdk #125
添加Tsc sdk

## ~~MinimalAPIs~~
* [ ] ~~Planning~~
~~规划中 (迁移到后续版本)~~

## ~~Observability(可观测性)~~
* [ ] ~~Support OpenTelemetry~~
~~支持OpenTelemetry 规划中 (迁移到后续版本)~~

## ~~Rule Engine(规则引擎)~~
* [ ] ~~Planning (Migrate to next version)~~
~~规划中 (迁移到下个版本)~~
